"""progressi del tutorial

Revisione: 0004
Precedente: 0003
Creata il: 2026-07-06 18:13:41.669013
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0004"
down_revision = "0003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "lesson_progress",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("lesson_code", sa.String(), nullable=False),
        sa.Column("last_step", sa.Integer(), nullable=False),
        sa.Column("completed", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "lesson_code"),
    )
    with op.batch_alter_table("lesson_progress", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_lesson_progress_lesson_code"), ["lesson_code"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_lesson_progress_user_id"), ["user_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("lesson_progress", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_lesson_progress_user_id"))
        batch_op.drop_index(batch_op.f("ix_lesson_progress_lesson_code"))

    op.drop_table("lesson_progress")
    # ### end Alembic commands ###
