"""analisi post-partita

Revisione: 0005
Precedente: 0004
Creata il: 2026-07-06 18:55:48.768531
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0005"
down_revision = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.add_column(sa.Column("analysis_json", sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("game_sessions", schema=None) as batch_op:
        batch_op.drop_column("analysis_json")

    # ### end Alembic commands ###
